- hosts: frontends
  gather_facts: true
  tasks:
  - name: debug ansible_facts
    debug: var=ansible_facts
    tags:
      - debug

  - name: Use Uri module for wrting smoke test.
    uri:
      url: "http://{{ item }}"
      return_content: yes
    loop: 
      - "{{ ansible_facts.hostname }}"
    register: webpage

  - name: debug webpage
    debug: var=webpage
    tags:
      - debug

  - name: Fail if 'Ansible has done its job' is not in the page content
    fail:
    when: "'Ansible has done its job' not in webpage.results[0].content"